# alpine :: azureci

name: $(date:yyyyMMdd)$(rev:.rr)

pr:
  - master

resources:
  containers:
    - container: nodejs
      image: node:alpine
      volumes:
        - /src:/nodejs

stages:
  stage: build
    displayName: stage::build
    jobs:
      - job: build_src
        displayName: 'build :: src'
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              echo 'build src'

  stage: test
    condition: succeeded('build')
    dependsOn: build
    displayName: stage::test
    jobs:
      - job: test_src
        displayName: 'test :: src'
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              echo 'test src'

  stage: pack
    condition: and(succeeded('test'), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    dependsOn: test
    displayName: stage::pack
    jobs:
      - job: pack_src
        displayName: 'pack :: src'
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              echo 'pack src'

  stage: deploy
    condition: and(succeeded('pack'), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    dependsOn: pack
    displayName: stage::deploy
    jobs:
      - job: deploy_src
        displayName: 'deploy :: src'
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              echo 'deploy src'

trigger:
  - master
