# room :: docker-compose

networks:
  room_localhost:
services:
  web:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    image: room
    depends_on:
      - data
    ports:
      - 14080:80
    networks:
      - room_localhost
    environment:
      ConnectionStrings__RoomDb: 'Host=data;Database=room;Username=postgres;Password=Pass@word'
  data:
    image: postgres:12.0
    networks:
      - room_localhost
    environment:
      POSTGRES_PASSWORD: 'Pass@word'
version: '3.7'
